// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

[Table("AudioBook")]
public partial class AudioBook
{
    [Key]
    public int AudioBookId { get; set; }

    [Required]
    public string Narrator { get; set; }

    [Required]
    public string AudioFormat { get; set; }

    [Required]
    public string Author { get; set; }

    [ForeignKey("AudioBookId")]
    [InverseProperty("AudioBook")]
    public virtual MediaLibrary AudioBookNavigation { get; set; }
}