// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

[Table("Book")]
[Index("ISBN", IsUnique = true)]
public partial class Book
{
    [Key]
    public int BookId { get; set; }

    [Required]
    public string Author { get; set; }

    [Required]
    public string ISBN { get; set; }

    [Required]
    public string Publisher { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("Book")]
    public virtual MediaLibrary BookNavigation { get; set; }
}