// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

[Table("Borrower")]
public partial class Borrower
{
    [Key]
    public int BorrowerId { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Address { get; set; }

    [Required]
    public string ContactNumber { get; set; }

    [Required]
    public string Email { get; set; }

    [InverseProperty("Borrower")]
    public virtual ICollection<LibraryTransaction> LibraryTransactions { get; set; } = new List<LibraryTransaction>();
}