// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

[Table("DVD")]
public partial class DVD
{
    [Key]
    public int DVDId { get; set; }

    [Required]
    public string Director { get; set; }

    public string Actors { get; set; }

    public string Subtitles { get; set; }

    [ForeignKey("DVDId")]
    [InverseProperty("DVD")]
    public virtual MediaLibrary DVDNavigation { get; set; }
}