// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

[Table("Genre")]
[Index("Name", IsUnique = true)]
public partial class Genre
{
    [Key]
    public int GenreId { get; set; }

    [Required]
    public string Name { get; set; }

    [InverseProperty("Genre")]
    public virtual ICollection<LibraryMedia> LibraryMedia { get; set; } = new List<LibraryMedia>();
}