// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

public partial class Medium
{
    [Key]
    public int MediaId { get; set; }

    [Required]
    public string Title { get; set; }

    [Column(TypeName = "BOOLEAN")]
    public bool IsAvailable { get; set; }

    [Required]
    public string MediaType { get; set; }

    [InverseProperty("BookNavigation")]
    public virtual Book Book { get; set; }

    [InverseProperty("DvdNavigation")]
    public virtual Dvd Dvd { get; set; }

    [InverseProperty("Media")]
    public virtual ICollection<LibraryTransaction> LibraryTransactions { get; set; } = new List<LibraryTransaction>();
}