// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library_Management_System.Entities;

[Table("MediaLibrary")]
public partial class MediaLibrary
{
    [Key]
    public int MediaId { get; set; }

    [Required]
    public string Title { get; set; }

    [Column(TypeName = "BOOLEAN")]
    public bool IsAvailable { get; set; }

    [Required]
    public string MediaType { get; set; }

    public string Description { get; set; }

    public int? Duration { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime CreationDate { get; set; }

    public string Language { get; set; }

    public int? GenreId { get; set; }

    [InverseProperty("AudioBookNavigation")]
    public virtual AudioBook AudioBook { get; set; }

    [InverseProperty("BookNavigation")]
    public virtual Book Book { get; set; }

    [InverseProperty("DVDNavigation")]
    public virtual DVD DVD { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("MediaLibraries")]
    public virtual Genre Genre { get; set; }

    [InverseProperty("Media")]
    public virtual ICollection<LibraryTransaction> LibraryTransactions { get; set; } = new List<LibraryTransaction>();
}